import { NextResponse } from "next/server";

let articles = [
  // Dummy articles list agar tum pehle se kuch add karna chaho
];

export async function POST(req) {
  const { title } = await req.json();
  const slug = title.toLowerCase().replace(/\s+/g, "-");
  const article = {
    slug,
    title,
    excerpt: `This is a short excerpt about ${title}`,
    content: `Full detailed article on ${title} generated by AI...`,
    media: ["https://via.placeholder.com/600x300"],
  };
  articles.push(article);
  return NextResponse.json(article);
}

export async function GET() {
  return NextResponse.json(articles);
}
